### ISSUE TITLE
[warning] failed package validation and/or copy for commit 86272daf29d7baf574acb8d978a74ffe6c3dea41

### ISSUE THREAD

**Issue by conda-forge-daemon** [conda-forge/jieba3k-feedstock#7]
Hi @conda-forge/jieba3k! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.

error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/linux-64/jieba3k-0.35.1-py37h9c2f6ca_1004.tar.bz2

**Comment by conda-forge-daemon** [comment]
Hi @conda-forge/jieba3k! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.


error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/linux-64/jieba3k-0.35.1-py36hd000896_1004.tar.bz2

**Comment by conda-forge-daemon** [comment]
Hi @conda-forge/jieba3k! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.


error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/linux-64/jieba3k-0.35.1-py39hf3d152e_1004.tar.bz2

**Comment by conda-forge-daemon** [comment]
Hi @conda-forge/jieba3k! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.


error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/osx-64/jieba3k-0.35.1-py38h50d1736_1004.tar.bz2

**Comment by conda-forge-daemon** [comment]
Hi @conda-forge/jieba3k! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.


error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/osx-64/jieba3k-0.35.1-py36h79c6626_1004.tar.bz2

**Comment by jakirkham** [comment]
Think this was fixed a while ago. Closing...
